### PR TITLE
Update pulpcore-selinux to 2.0.0

### PR DESCRIPTION
**Pull request by Odilhao**
(cherry picked from commit aa5adc906adf40ec911559f01816e45e269baecc)

### CODE REVIEW

**Review by zjhuntin — APPROVED** [review]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by Odilhao** [comment]
We need a regen-repo here, running

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Pull request merged**
