### PR TITLE
Python 3.8 rebuild: stage three

### PR DESCRIPTION
**Pull request by evgeni**
needs #240 and #241 ;)

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Review by pcreech — APPROVED** [review]
ACK pending pipe (repoclosure fail expected)

**Comment by evgeni** [comment]
I dropped yarl from this PR, as it needs typing-extensions, which is in this PR…

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
same with aioredis, because I can't grep

**Pull request merged**
