### PR TITLE
Remove EL7 SCL macros and declare postgresql-evr as noarch

### PR DESCRIPTION
**Pull request by ekohl**
Additionally this uses more macros to replace the name and version.

The postgresql-devel build requirement is dropped since it's redundant and actually broke the build on Fedora.

### CODE REVIEW

**Comment by ekohl** [comment]
```
DEBUG util.py:634:  No matching package to install: 'postgresql-server-devel'
```

However, this does appear to be in EL8. On a random container:
```console
# dnf info postgresql-server-devel
Last metadata expiration check: 0:00:29 ago on Fri Jan 20 13:47:15 2023.
Available Packages
Name         : postgresql-server-devel
Version      : 10.19
Release      : 1.module_el8.6.0+1047+4202cf9a
Architecture : x86_64
Size         : 1.1 M
Source       : postgresql-10.19-1.module_el8.6.0+1047+4202cf9a.src.rpm
Repository   : appstream
Summary      : PostgreSQL development header files and libraries
URL          : http://www.postgresql.org/
License      : PostgreSQL
Description  : The postgresql-server-devel package contains the header files and libraries
             : needed to compile C or C++ applications which will directly interact
             : with a PostgreSQL database management server.  It also contains the ecpg
             : Embedded C Postgres preprocessor. You need to install this package if you want
             : to develop applications which will interact with a PostgreSQL server.
# dnf module enable postgresql:12
Last metadata expiration check: 0:01:16 ago on Fri Jan 20 13:47:15 2023.
Dependencies resolved.
===============================================================================================================================================================
 Package                               Architecture                         Version                                Repository                             Size
===============================================================================================================================================================
Enabling module streams:
 postgresql                                                                 12                                                                                

Transaction Summary
===============================================================================================================================================================

Is this ok [y/N]: y
Complete!
# dnf info postgresql-server-devel
Last metadata expiration check: 0:01:19 ago on Fri Jan 20 13:47:15 2023.
Available Packages
Name         : postgresql-server-devel
Version      : 12.12
Release      : 1.module_el8.6.0+1219+2bd8590a
Architecture : x86_64
Size         : 1.2 M
Source       : postgresql-12.12-1.module_el8.6.0+1219+2bd8590a.src.rpm
Repository   : appstream
Summary      : PostgreSQL development header files and libraries
URL          : http://www.postgresql.org/
License      : PostgreSQL
Description  : The postgresql-server-devel package contains the header files and configuration
             : needed to compile PostgreSQL server extension.
```

**Comment by evgeni** [comment]
I *think* this is because the build tag doesn't have the postgresql module available at all:

http://koji.katello.org/koji/taginfo?tagID=pulpcore-3.21-el8-build

* [flat-base-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=91)
* [flat-python36-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=93)
* [flat-python39-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=98)
* [flat-python39-devel-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=99)
* [flat-ruby27-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=87)
* [flat-swig30-el8](http://koji.katello.org/koji/externalrepoinfo?extrepoID=97)

**Comment by ekohl** [comment]
Let's see if a plain rebuild works: https://github.com/theforeman/pulpcore-packaging/pull/611

**Comment by ekohl** [comment]
Looks like this PR is less red since at least EL9 builds. @Odilhao could you take a look?

**Comment by ekohl** [comment]
Submitted against rpm/3.28: https://github.com/theforeman/pulpcore-packaging/pull/724

**Pull request closed without merging**
