### PR TITLE
Bump pulp-rpm to 3.26.1

### PR DESCRIPTION
**Pull request by ianballou**
Other PRs:
https://github.com/Katello/katello/pull/11057
https://github.com/theforeman/foreman-packaging/pull/10981
https://github.com/theforeman/foreman-packaging/pull/10982

### CODE REVIEW

**Comment by Odilhao** [comment]
This one needs libcomps update, I'll work on that later today

**Comment by Odilhao** [comment]
This one needs https://github.com/theforeman/pulpcore-packaging/pull/1042 and https://github.com/theforeman/pulpcore-packaging/pull/1043

**Comment by Odilhao** [comment]
We need to update this line 
[Requires:       python%{python3_pkgversion}-createrepo_c >= 1.0.1](https://github.com/theforeman/pulpcore-packaging/blob/67bc2aca303df11922881d6ec1510d2a6f868b2a/packages/python-pulp-rpm/python-pulp-rpm.spec#L34)
to `Requires:       python%{python3_pkgversion}-createrepo_c >= 1.1.0`

and this one

https://github.com/theforeman/pulpcore-packaging/blob/67bc2aca303df11922881d6ec1510d2a6f868b2a/packages/python-pulp-rpm/python-pulp-rpm.spec#L35

to `Conflicts:      python%{python3_pkgversion}-createrepo_c >= 1.2.0`

**Comment by ianballou** [comment]
@Odilhao I bumped the @Odilhao I've updated the libcomps and createrepo_c requirements.

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
