### PR TITLE
add packages for google-cloud-storage

### PR DESCRIPTION
**Pull request by dmaes**
An attempt at a PR for #1244 . Not entirely sure if I did it correctly, especially with the git-annex stuff, please let me know if I need to fix something.

### CODE REVIEW

**Comment by Odilhao** [comment]
Thanks for adding the packages @dmaes , looking at the files I can see that the script generated the `scl` bits that we don't use due to EL7 being deprecated, we need to remove all scl reference and google packages always explode the build requires with the protobuf section, I'll do some review later today and trim the spec files. 

We also need some e-mail in the specfile changelog, atm it's only showing the date.

**Comment by dmaes** [comment]
@Odilhao thanks for taking a look. I fixed the changelogs already.

**Comment by Odilhao** [comment]
ok to test

**Comment by Odilhao** [comment]
@dmaes I'm finishing locally the addition of 2 packages `rsa` and `cachetools` I believe that after adding those 2 we will have all the necessary packages.

**Review by Odilhao — APPROVED** [review]

**Comment by Odilhao** [comment]
Repoclosure failed because we don't have the packages published, all builds passed, merging.

**Pull request merged**
