### PR TITLE
Update pulp_deb to 2.9.2 (pulpcore 3.7 repo)

### PR DESCRIPTION
**Pull request by quba42**
Needs to be coordinated with:
- https://github.com/theforeman/foreman-packaging/pull/6588
- https://github.com/Katello/katello/pull/9329
- The Katello 3.18.4 release

### CODE REVIEW

**Comment by jlsherrill** [comment]
You're missing one step, you need to wget the tarball from pypi, git annex add it, and then git rm the old one.

**Comment by quba42** [comment]
> You're missing one step, you need to wget the tarball from pypi, git annex add it, and then git rm the old one.

I am trying out the `obal` tooling right now. Looks like I am still missing some dependencies though.

**Comment by quba42** [comment]
Manual `git annex` commands is easier after all than trying to get `obal` to work on a Debian host...

**Comment by quba42** [comment]
Do not merge until I have figured out if this requires new API bindings on the Katello side!

**Comment by quba42** [comment]
Updated the PR to update to 2.9.2 instead of 2.9.1. This is exactly the same bindings wise, but includes an important bugfix.

**Comment by jturel** [comment]
[test rpm]

**Comment by quba42** [comment]
Rebased to the tip of the `rpm/3.7` branch one more time.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
