### PR TITLE
Add Requires and Conflicts for Jinja2 to reflect the change done for 3.15.8+

### PR DESCRIPTION
**Pull request by Odilhao**
Required now by Pulpcore 3.15.9 https://github.com/pulp/pulpcore/blob/425615ecb11464b2703ce59d8d064805d85ef347/requirements.txt#L23

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[rpm test]

**Comment by Odilhao** [comment]
[test rpm]

**Review by pcreech — APPROVED** [review]

**Pull request merged**
