### PR TITLE
pulp-cli for 3.9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by pcreech — APPROVED** [review]
ACK

**Comment by pcreech** [comment]
```
[2021-07-01T14:35:14.169Z]       unresolved deps:

[2021-07-01T14:35:14.169Z]         python3-requests >= 2.25.1

[2021-07-01T14:35:14.169Z]         python3-PyYAML >= 5.4.1
```

**Comment by evgeni** [comment]
Yes, yes I know. Talking to pulp how to avoid that.

**Comment by evgeni** [comment]
waiting on https://github.com/pulp/pulp-cli/pull/296

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
@evgeni this appears to need python3-PyYAML >= 5.4.1, and python3-requests >= 2.25.1 to build the rpm

**Comment by zjhuntin** [comment]
Ah never mind, I see what needs to be merged

**Comment by zjhuntin** [comment]
[test rpm]

**Pull request merged**
