### PR TITLE
Adding packages for Galaxy-ng 4.5.2

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by Odilhao** [comment]
Repoclosure is expected to fail due to semantic_version being update here and not in a another PR

**Comment by Odilhao** [comment]
Needs #553 for a clean scratch

**Comment by Odilhao** [comment]
[test rpm]

**Review by zjhuntin — APPROVED** [review]

**Comment by Odilhao** [comment]
```
koji add-pkg --owner kojiadm  pulpcore-3.18-el8 python-ldap python-django-auth-ldap
Adding 2 packages to tag pulpcore-3.18-el8
 koji add-pkg --owner kojiadm  pulpcore-3.18-el9 python-ldap python-django-auth-ldap
Adding 2 packages to tag pulpcore-3.18-el9
```

**Pull request merged**
