### PR TITLE
Bump pulp-rpm to 3.18.9

### PR DESCRIPTION
**Pull request by ianballou**
To fix the issue reported here: https://community.theforeman.org/t/sync-errors-on-all-syncs-including-the-initial-sync-between-new-katello-server-and-content-proxy/29577/19

### CODE REVIEW

**Review by Odilhao — APPROVED** [review]
We can merge this tomorrow

**Comment by ianballou** [comment]
Looks like centos-stream 9 is having some repository-related issues. I saw a 404 on a kernel RPM...

**Comment by dralley** [comment]
@Odilhao There is a BZ for this also that is tagged for 6.12.z  https://bugzilla.redhat.com/show_bug.cgi?id=2077363

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Pull request merged**
