### PR TITLE
Bump python-cryptography to 3.4.8

### PR DESCRIPTION
**Pull request by evgeni**
needs #246

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
Great, modern Cryptography needs OpenSSL 1.1, but EL7 is stuck on 1.0. :fire:

**Comment by evgeni** [comment]
Let's discuss this in https://pulp.plan.io/issues/9367

**Comment by Odilhao** [comment]
With 3.18 being the 1st release to not have EL7, should we bump this on 3.18?

**Comment by evgeni** [comment]
Sounds like a solid idea. Feel free to take over this PR :)

**Comment by evgeni** [comment]
Closing in favor of https://github.com/theforeman/pulpcore-packaging/pull/460

**Pull request closed without merging**
