### PR TITLE
Remove EL7 SCL macros and declare evr as noarch

### PR DESCRIPTION
**Pull request by ekohl**
Additionally this uses more macros to replace the name and version.

The postgresql-devel build requirement is dropped since it's redundant and actually broke the build on Fedora.

This is the same patch as https://github.com/theforeman/pulpcore-packaging/pull/600 but that never got attention and submitting this against rpm/3.28.

### CODE REVIEW

**Comment by evgeni** [comment]
```
DEBUG util.py:634:  No matching package to install: 'postgresql-server-devel'
```

**Comment by Odilhao** [comment]
Yay another repo needs to be add as flat on koji https://github.com/theforeman/foreman-infra/pull/1921

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
```
make: pg_config: Command not found
make: *** No rule to make target 'install'.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.sWktda (%install)
``` 
New error yay

**Comment by ekohl** [comment]
Weird, `postgresql-server-devel` doesn't depend on `libpq-devel`.

**Comment by ekohl** [comment]
Euh, this doesn't look good.
```
DEBUG util.py:444:   Problem: libpq-devel-13.2-4.el9.i686 from build  does not belong to a distupgrade repository
DEBUG util.py:444:    - conflicting requests
DEBUG util.py:444:    - package postgresql-server-devel-13.10-1.el9.x86_64 from build requires postgresql-private-devel, but none of the providers can be installed
DEBUG util.py:444:    - package postgresql-server-devel-13.11-1.el9.x86_64 from build requires postgresql-private-devel, but none of the providers can be installed
DEBUG util.py:444:    - package postgresql-server-devel-13.3-10.el9.x86_64 from build requires postgresql-private-devel, but none of the providers can be installed
DEBUG util.py:444:    - package postgresql-server-devel-13.5-1.el9.x86_64 from build requires postgresql-private-devel, but none of the providers can be installed
DEBUG util.py:444:    - package postgresql-server-devel-13.7-1.el9.x86_64 from build requires postgresql-private-devel, but none of the providers can be installed
DEBUG util.py:444:    - package postgresql-private-devel-13.10-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.2-4.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.11-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.2-4.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.3-10.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.2-4.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.5-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.2-4.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.7-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.2-4.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-15.0-1.module_el9+254+28357c0e.x86_64 from build is filtered out by modular filtering
DEBUG util.py:444:    - package postgresql-private-devel-15.2-1.module_el9+264+92dde3f0.x86_64 from build is filtered out by modular filtering
DEBUG util.py:444:    - package postgresql-server-devel-15.0-1.module_el9+254+28357c0e.x86_64 from build is filtered out by modular filtering
DEBUG util.py:444:    - package postgresql-server-devel-15.2-1.module_el9+264+92dde3f0.x86_64 from build is filtered out by modular filtering
DEBUG util.py:444:    - libpq-devel-13.5-1.el9.i686 from build  does not belong to a distupgrade repository
DEBUG util.py:444:    - package postgresql-private-devel-13.10-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.5-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.11-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.5-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.3-10.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.5-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.5-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.5-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.7-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.5-1.el9.x86_64 from build
DEBUG util.py:444:    - libpq-devel-13.11-1.el9.i686 from build  does not belong to a distupgrade repository
DEBUG util.py:444:    - package postgresql-private-devel-13.10-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.11-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.11-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.11-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.3-10.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.11-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.5-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.11-1.el9.x86_64 from build
DEBUG util.py:444:    - package postgresql-private-devel-13.7-1.el9.x86_64 from build conflicts with libpq-devel provided by libpq-devel-13.11-1.el9.x86_64 from build
```

**Comment by Odilhao** [comment]
I think we only need `libpq-devel` for EL8, the scratch for EL8 worked.

**Comment by ekohl** [comment]
Hmm, then we didn't need the PG 12 module at all?

**Comment by Odilhao** [comment]
Yes, looks like we don't need the flat module.

**Comment by Odilhao** [comment]
Nevermind, we do need postgres-server-devel:

```
+ cd postgresql-evr-0.0.2
+ rm -rf /builddir/build/BUILDROOT/postgresql-evr-0.0.2-2.el8.noarch
+ /usr/bin/make install DESTDIR=/builddir/build/BUILDROOT/postgresql-evr-0.0.2-2.el8.noarch 'INSTALL=/usr/bin/install -p'
Makefile:6: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target '/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.IZ7qe8 (%install)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.IZ7qe8 (%install)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 789, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
```

**Comment by ekohl** [comment]
Ah, on EL9 we need CRB to be enabled for `postgresql-server-devel` to be installable.

**Comment by ekohl** [comment]
<del>Now with conditionals it's green. I didn't test on Fedora, but I'm treating it like EL9.</del>

I swear it was green. I blame GH for not refreshing.

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
