### PR TITLE
pulpcore 3.13

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by quba42 — APPROVED** [review]
Just wanted to state that this is the right pulp_deb version for pulpcore 3.13.
I guess I just need to be quick about releasing after each new pulpcore release for the automation to take care of things on its own.

**Comment by evgeni** [comment]
needs #172 and #173

thanks @quba42, sounds like it :)

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
repoclosure expected, unpublished repo.

**Review by pcreech — APPROVED** [review]
ACK

**Pull request merged**
