### PR TITLE
Rebuilding for 3.9 from e to h

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by Spredzy** [comment]
This is required to land https://github.com/theforeman/pulpcore-packaging/pull/458 before this one can be re-run

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Spredzy** [comment]
@Odilhao your comment did not retrigger the CI

**Comment by zjhuntin** [comment]
ACK

**Review by zjhuntin — APPROVED** [review]

**Pull request merged**
