### PR TITLE
add pulp-manifest package

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by goosemania** [comment]
Yay! Thanks!

**Comment by quba42** [comment]
What does this package do?

**Comment by goosemania** [comment]
> What does this package do?

https://github.com/pulp/pulp-manifest#readme

**Review by pcreech — APPROVED** [review]

**Comment by sbernhard** [comment]
Should this part of rpm/3.16, rpm/3.18, and develop, too? @Odilhao

**Comment by Odilhao** [comment]
> Should this part of rpm/3.16, rpm/3.18, and develop, too? @Odilhao

Yes, it should, theres one PR for 3.16, I need to open another one for 3.18

**Comment by sbernhard** [comment]
Ah, nice. Thanks.

**Pull request merged**
