### PR TITLE
Use -fno-strict-aliasing for python-pycares

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by evgeni** [comment]
Why?

**Review by Odilhao — APPROVED** [review]

**Comment by pcreech** [comment]
> Why?

The build log without the compiler flag has:

```
deps/c-ares/src/lib/ares__sortaddrinfo.c: In function 'get_label':
deps/c-ares/src/lib/ares__sortaddrinfo.c:166:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       else if (ARES_IN6_IS_ADDR_TEREDO(&addr6->sin6_addr))
       ^
deps/c-ares/src/lib/ares__sortaddrinfo.c: In function 'get_precedence':
deps/c-ares/src/lib/ares__sortaddrinfo.c:227:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       else if (ARES_IN6_IS_ADDR_TEREDO(&addr6->sin6_addr))
```

And was being flagged by some utilities.  This was the fix that was suggested to resolve the issue.

**Comment by evgeni** [comment]
Thanks for updating the commit message!

**Comment by pcreech** [comment]
Was an unintentional oversight :D

**Pull request merged**
