### PR TITLE
Add provides pulp-manifest

### LINKED ISSUE #1038: Provide a more user-friendly way to install pulp_manifest
original idea by Ewoud:

              We already rebuilt against Python 3.11 some time ago so is already wrong:
https://github.com/theforeman/pulpcore-packaging/blob/32305a4c9598019f6756c17f3af23a9beb28c9af/packages/python-pulp_manifest/python-pulp_manifest.spec#L65-L66

We should really add a `Provides: pulp-manifest` to it so users can always run `dnf install pulp-manifest`, regardless of the Python version.

cc @Odilhao

_Originally posted by @ekohl in https://github.com/theforeman/foreman-documentation/pull/3086#discussion_r1649015064_

### PR DESCRIPTION
**Pull request by Odilhao**
Closes https://github.com/theforeman/pulpcore-packaging/issues/1038

### CODE REVIEW

**Comment by Odilhao** [comment]
@ekohl @maximiliankolb would this help with that issue?

**Review by ekohl — APPROVED** [review]
Yes, I think so.

**Review by maximiliankolb — APPROVED** [review]
Thanks, LGTM

**Comment by ekohl** [comment]
@Odilhao can we backport this to a stable release so at least for Foreman nightly we can start to document this?

**Comment by Odilhao** [comment]
> @Odilhao can we backport this to a stable release so at least for Foreman nightly we can start to document this?

Done for [3.49](https://github.com/theforeman/pulpcore-packaging/pull/1072) and [3.39](https://github.com/theforeman/pulpcore-packaging/pull/1073)

**Pull request merged**
