### PR TITLE
Switch to using Koji directly for builds and drop tito

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Are there any other active branches worth making this change to?

Note this change also comes with the tagging of existing builds when running `obal release`

**Comment by Odilhao** [comment]
The active ones are 3.17, 3.16, 3.15(GalaxyNg) 3.14

**Comment by ehelms** [comment]
OK, I'll start here and move to those once we've agreed on and have a model PR for the change.

**Review by Odilhao — APPROVED** [review]

**Comment by ehelms** [comment]
@Odilhao I will let you merge this when you are ready to start using it

**Comment by ekohl** [comment]
Is this still relevant? It's on an old branch and it's been over a year.

**Comment by Odilhao** [comment]
Closing this, since we already stopped using tito, and 3.18 is not supported anymore.

**Pull request closed without merging**
