### PR TITLE
Fixup outstanding dependency issues with Pulp 3.17

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by Odilhao** [comment]
I don't know if we need to bump django-readonly-field, if it shows as necessary this is the package that we need to force the scm usage during the prep or install

**Comment by pcreech** [comment]
@Odilhao  This PR is to address the repoclosure issues seen here: https://ci.theforeman.org/blue/organizations/jenkins/pulpcore-3.17-rpm-pipeline/detail/pulpcore-3.17-rpm-pipeline/31/pipeline/

django-readonly-field is not mentioned in this repoclosure failure

**Comment by Odilhao** [comment]
[test rpm]

**Review by Odilhao — APPROVED** [review]

**Comment by pcreech** [comment]
Repoclosure failures are the ones addressed by this PR.  Merging

**Pull request merged**
