### PR TITLE
pulpcore-selinux 1.1.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
note to self (and @pcreech I guess), I had to untag `python-iniparse` from the el7 tag as it otherwise failed to build due to "yum needs python-iniparse" and somehow our iniparse got in the way (and we only build py3 bindings)

full error:

```
DEBUG util.py:598:  Getting requirements for pulpcore-selinux-1.1.0-1.el7.src
DEBUG util.py:598:   --> checkpolicy-2.5-8.el7.x86_64
DEBUG util.py:598:   --> selinux-policy-devel-3.13.1-266.el7.noarch
DEBUG util.py:598:  Error: Package: yum-3.4.3-167.el7.centos.noarch (build)
DEBUG util.py:598:             Requires: python-iniparse
```

**Comment by evgeni** [comment]
repoclosure is expected, the repo has not been published yet.

**Review by pcreech — APPROVED** [review]
ACK

**Comment by evgeni** [comment]
Updated to 1.1.1 which contains a tiny fix for upgrades.

**Pull request merged**
