### PR TITLE
pulp-rpm 3.15 and deps

### PR DESCRIPTION
**Pull request by evgeni**
requires #267

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
```
[2021-09-13T13:45:34.482Z]       unresolved deps:
[2021-09-13T13:45:34.482Z]         tfm-pulpcore-python3-createrepo-c >= 0.17.0
[2021-09-13T13:45:34.482Z]         tfm-pulpcore-python3-libcomps >= 0.1.15
[2021-09-13T13:45:34.482Z]         tfm-pulpcore-python3-productmd >= 1.33.0
[2021-09-13T13:45:34.482Z]         tfm-pulpcore-python3-solv >= 0.7.17
```

Need to work on these.

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
```
[2021-09-29T07:19:34.035Z]       unresolved deps:
[2021-09-29T07:19:34.035Z]         tfm-pulpcore-python3-createrepo-c >= 0.17.0
```

coming close!

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
:green_apple:

**Review by zjhuntin — APPROVED** [review]

**Comment by jlsherrill** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Pull request merged**
