### PR TITLE
Update pulp-rpm to 3.18.3

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by Odilhao** [comment]
Don't you want the freshest one? https://github.com/theforeman/pulpcore-packaging/commit/cc320c46f6c3ba835421546ba0b03b1f68cbbdce aka Pulp-rpm 3.18.5

**Comment by pcreech** [comment]
@Odilhao nope, specific current need is to have 3.18.3 on the 3.18 branch

**Review by Odilhao — APPROVED** [review]

**Comment by Odilhao** [comment]
```
package: python3-pulp-rpm-3.18.3-1.el9.noarch from downloaded_rpms
[2022-10-03T18:33:20.625Z]       unresolved deps:
[2022-10-03T18:33:20.626Z]         (python3.9dist(createrepo-c) >= 0.20.1 with python3.9dist(createrepo-c) < 0.21)
```

Need to cherry-pick this one https://github.com/theforeman/pulpcore-packaging/pull/581/commits/fa635560fedd58794ad5fd16c66c0dd45c0e00c8

**Comment by Odilhao** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Pull request merged**
