### PR TITLE
Update python-pkginfo to 1.11.0

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by pcreech** [comment]
Looks like python-pulp-python conflicts on versions higher than 1.9.7

https://github.com/theforeman/pulpcore-packaging/blob/rpm/develop/packages/python-pulp-python/python-pulp-python.spec#L36

**Comment by Odilhao** [comment]
> Looks like python-pulp-python conflicts on versions higher than 1.9.7
> 
> 
> 
> https://github.com/theforeman/pulpcore-packaging/blob/rpm/develop/packages/python-pulp-python/python-pulp-python.spec#L36

Aha look here https://github.com/theforeman/pulpcore-packaging/pull/1170 it will be required by the next pulp-python release 🐔🥚🐣

**Comment by pcreech** [comment]
We'll probably want to wait to merge this one till after the new pulp-python is merged.  but otherwise, ack!

**Comment by Odilhao** [comment]
pulp-python is merged, merging this one to have a clean release

**Pull request merged**
