### PR TITLE
Copr add support

### PR DESCRIPTION
**Pull request by ehelms**
"requires" https://github.com/theforeman/pulpcore-packaging/pull/711 first, as I found those while trying to rebuild for Copr.

I have broken up the packages into groups per my findings trying to build from scratch to make it easier. If this breaks tooling and automation let me know and I'll think about how to handle this.

This PR does *not* change to Copr, that requires adding `build_package_build_system=copr` and this simply adds the ability to release to Copr.  I tested this and built 3.28 out here: https://copr.fedorainfracloud.org/coprs/g/theforeman/pulpcore-3.28-staging/builds/

I have not yet tested whether these builds work.

### CODE REVIEW

**Comment by Odilhao** [comment]
Looks like we need module metadata? 

```
dnf install python39-pulpcore
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:01:02 ago on Mon Sep  4 13:44:12 2023.
Error: 
 Problem: package python39-pulpcore-3.28.10-7.el8.noarch requires python39-cryptography >= 38.0.1, but none of the providers can be installed
  - conflicting requests
  - package python39-cryptography-38.0.4-1.el8.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I can see the build for [cryptography](https://copr.fedorainfracloud.org/coprs/g/theforeman/pulpcore-3.28-staging/build/6364024/), if I try to force the manual install it will try to get the build from `appstream`:

```
dnf install python39-cryptography       
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:02:39 ago on Mon Sep  4 13:44:12 2023.
Dependencies resolved.
=======================================================================================================================================================================================================================================
 Package                                                        Architecture                                Version                                                               Repository                                      Size
=======================================================================================================================================================================================================================================
Installing:
 python39-cryptography                                          x86_64                                      3.3.1-2.module_el8+639+3fcd10de                                       appstream                                      637 k
Installing dependencies:
 python39                                                       x86_64                                      3.9.17-2.module_el8+639+3fcd10de                                      appstream                                       34 k
 python39-cffi                                                  x86_64                                      1.14.3-2.module_el8+639+3fcd10de                                      appstream                                      261 k
 python39-idna                                                  noarch                                      2.10-3.module_el8+639+3fcd10de                                        appstream                                       92 k
 python39-libs                                                  x86_64                                      3.9.17-2.module_el8+639+3fcd10de                                      appstream                                      8.7 M
 python39-pip-wheel                                             noarch                                      20.2.4-8.module_el8+639+3fcd10de                                      appstream                                      1.1 M
 python39-ply                                                   noarch                                      3.11-10.module_el8+639+3fcd10de                                       appstream                                      114 k
 python39-pycparser                                             noarch                                      2.20-3.module_el8+639+3fcd10de                                        appstream                                      140 k
 python39-setuptools-wheel                                      noarch                                      50.3.2-4.module_el8+639+3fcd10de                                      appstream                                      497 k
 python39-six                                                   noarch                                      1.15.0-3.module_el8+639+3fcd10de                                      appstream                                       41 k
Installing weak dependencies:
 python39-pip                                                   noarch                                      20.2.4-8.module_el8+639+3fcd10de                                      appstream                                      2.1 M
 python39-setuptools                                            noarch                                      50.3.2-4.module_el8+639+3fcd10de                                      appstream                                      969 k
Enabling module streams:
 python39                                                                                                   3.9                                                                                                                       

Transaction Summary
=======================================================================================================================================================================================================================================
Install  12 Packages

Total download size: 15 M
Installed size: 50 M
Is this ok [y/N]: n
Operation aborted.
```

**Comment by ehelms** [comment]
The repositories are not intended to be used directly from Copr due to their lack of modularity support. I've developed a workflow that I have tested for Foreman, it is basically:


Clone packaging (Jenkins node) -> Reposync from Copr (Jenkins node) -> Filter repository and add modularity (Jenkins node) -> SCP repository to stagingyum.theforeman.org (Jenkins node to web02)

The repositories for testing end up here:

https://stagingyum.theforeman.org/

**Comment by Odilhao** [comment]
@ehelms I'm not seeing any `hatch` related package in the tiers for copr, is this intended?

**Comment by ehelms** [comment]
> @ehelms I'm not seeing any `hatch` related package in the tiers for copr, is this intended?

https://github.com/theforeman/pulpcore-packaging/pull/712/files#diff-8ad9be659ee8845f6bafa3ccc4f6c016ed683ebb9fb192ae9d1438613a8206fcR254-R257

The diff just is confusing, it's in Tier 4.

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
