### PR TITLE
Update pulp-cli-deb to 0.0.7

### PR DESCRIPTION
**Pull request by quba42**

### CODE REVIEW

**Comment by quba42** [comment]
In order to upgrade to this version we need to add the new dependency `pulp-glue-deb` from here: https://pypi.org/project/pulp-glue-deb/

However, I don't know how to generate an initial SPEC file from the pypi package.

@Odilhao Any help would be appreciated!

**Comment by Odilhao** [comment]
Sorry for the delay @quba42 heres the PR to add the glue-deb package https://github.com/theforeman/pulpcore-packaging/pull/907

**Comment by quba42** [comment]
@Odilhao I updated this PR to reflect the presence of pulp-glue-deb.

It is now ready for review.

**Comment by Odilhao** [comment]
Thanks, looks like we don't have setup.py anymore, only pyproject.toml, we will need to update the setup, build and install section, do you mind if I take over the PR?

**Comment by Odilhao** [comment]
Closing this one to keep at https://github.com/theforeman/pulpcore-packaging/pull/911

**Pull request closed without merging**
