### PR TITLE
Bump python-pulp-deb to 2.16.0 for rpm/3.16

### PR DESCRIPTION
**Pull request by quba42**
Pulpcore 3.16 should use pulp_deb 2.16!

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Hi @quba42 

Could you also update the line 5 at https://github.com/theforeman/pulpcore-packaging/blob/890d89a0f7f6c0eaecf84765dffc30517ade47b0/automation/requirements.txt#L5

Changing from 2.15.0 to 2.16.0

**Comment by quba42** [comment]
@Odilhao done. Is this a new file? (I don't think I have noticed it before).

**Comment by Odilhao** [comment]
We have this file since last year, and it's mostly used for our automation during versions bump of pulpcore, @evgeni knows better about it.

Thanks for updating the file.

**Comment by evgeni** [comment]
Yeah, we usually didn't ask anyone to update it, but did so manually every now and then. It's only needed when using the container based "update all the packages" process.

**Comment by Odilhao** [comment]
We need #332 to be merged first.

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Hi @quba42 could you please rebase your local branch against rpm/3.16 again? We did some packages bumps and looks like this branch is a little outdated. 

Sorry for that

**Review by Odilhao — APPROVED** [review]

**Comment by Odilhao** [comment]
Thanks @quba42 merging now

**Pull request merged**
