### PR TITLE
Bump version of python-distro to rebuild with python3 build name

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by Odilhao** [comment]
The package with the nvr 1.7.0-4 already exists in our repo https://yum.theforeman.org/pulpcore/3.49/el8/x86_64/python3.11-distro-1.7.0-4.el8.noarch.rpm

**Comment by pcreech** [comment]
How is that causing a problem at the moment?

**Comment by Odilhao** [comment]
> How is that causing a problem at the moment?

Repodata atm is wonky with the same nvr for the old `python-distro` and the new `python3-distro` on copr:

```
[MIRROR] python3.11-distro-1.7.0-4.el9.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: 20b49f6b16eadd8724472751752ab05cd170c4761651ce556c8b3a9e04d57937(sha256)  Expected: 530814db11e77c1acffd803f1d2cf32cef1b9624cee45e2b9b41eb40a51e1de9(sha256) 
[MIRROR] python3.11-distro-1.7.0-4.el9.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: 20b49f6b16eadd8724472751752ab05cd170c4761651ce556c8b3a9e04d57937(sha256)  Expected: 530814db11e77c1acffd803f1d2cf32cef1b9624cee45e2b9b41eb40a51e1de9(sha256) 
[MIRROR] python3.11-distro-1.7.0-4.el9.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: 20b49f6b16eadd8724472751752ab05cd170c4761651ce556c8b3a9e04d57937(sha256)  Expected: 530814db11e77c1acffd803f1d2cf32cef1b9624cee45e2b9b41eb40a51e1de9(sha256) 
[MIRROR] python3.11-distro-1.7.0-4.el9.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: 20b49f6b16eadd8724472751752ab05cd170c4761651ce556c8b3a9e04d57937(sha256)  Expected: 530814db11e77c1acffd803f1d2cf32cef1b9624cee45e2b9b41eb40a51e1de9(sha256) 
```

**Comment by pcreech** [comment]
Cool.  Thanks for the explanation!  merging

**Pull request merged**
