### PR TITLE
build libsolv against Python 3.8 

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
needs https://github.com/theforeman/tool_belt/pull/405 for EL8 build

**Comment by evgeni** [comment]
"Version updated but release was not reset back to 1 for libsolv"

Stupid linter check is stupid.

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
Progress!
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/libsolv-0.7.20-2.el8.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib64/python3.8/site-packages/__pycache__/solv.cpython-38.opt-1.pyc
   /usr/lib64/python3.8/site-packages/__pycache__/solv.cpython-38.pyc
    Installed (but unpackaged) file(s) found:
   /usr/lib64/python3.8/site-packages/__pycache__/solv.cpython-38.opt-1.pyc
   /usr/lib64/python3.8/site-packages/__pycache__/solv.cpython-38.pyc
RPM build errors:
```

**Comment by evgeni** [comment]
I don't understand why it's not created on el7 tho…

**Comment by pcreech** [comment]
swig is 2.0 on el7, 3.0 on el8.  Just a shot in the dark, but that could explain it.  I've seen _weirdness_ with inconsistent output between the versions of swig like that.

**Review by pcreech — APPROVED** [review]
Swig output differences aside, I've looked at the rpms and everything looks ok.  Should be good to merge.

**Comment by evgeni** [comment]
The pycache is there if built outside the SCL, that's what weirds me out...

**Pull request merged**
