### PR TITLE
Update pulpcore-selinux to 1.2.4

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@evgeni Do you know what voodoo will correct the EL7 builds?

**Comment by evgeni** [comment]
Untag python-iniparse, I thought I did that when I renamed the pkg to python3-iniparse

**Comment by evgeni** [comment]
[test rpm]

I only fixed that in 3.7. not later :facepalm: 

is there a reason not to backport this change to 3.7? or is that only relevant for el8 deployments with katello, which we didn't before 3.9?

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
I certainly think this should be backported to 3.7 but I first wanted to get this into 3.9, or even build for that matter.

**Pull request merged**
