### PR TITLE
Update pulp_deb to 2.9.1 (pulpcore 3.9 repo)

### PR DESCRIPTION
**Pull request by quba42**

### CODE REVIEW

**Comment by jlsherrill** [comment]
do you mind adding a PR for 3.11 too?

**Comment by quba42** [comment]
> do you mind adding a PR for 3.11 too?

Working on it.

**Comment by quba42** [comment]
Do not merge until I have figured out if this requires new API bindings on the Katello side!

**Comment by jlsherrill** [comment]
after some discussion, we're going to merge this for 4.0 now while we get the 4.0.1 release out

**Pull request merged**
