### PR TITLE
pulp-cli for 3.7

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by pcreech — APPROVED** [review]
ACK

**Comment by pcreech** [comment]
```
[2021-07-01T14:32:18.446Z]       unresolved deps:

[2021-07-01T14:32:18.446Z]         python3-PyYAML >= 5.4.1

[2021-07-01T14:32:18.446Z]         python3-requests >= 2.25.1
```

**Comment by evgeni** [comment]
waiting on https://github.com/pulp/pulp-cli/pull/296

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Pull request merged**
