### PR TITLE
add pulp-manifest package

### PR DESCRIPTION
**Pull request by Odilhao**
(cherry picked from commit 9d5507f5ce9e23723e32dffc03569466658c7ac0)

### CODE REVIEW

**Review by zjhuntin — APPROVED** [review]

**Review by sbernhard — APPROVED** [review]

**Review by goarsna — APPROVED** [review]
I can approve these changes. It would be really great to have the pulp-manifest package in pulpcore 3.16 as we really require this.

Is there anything to do for this being merged asap? :see_no_evil:

**Review by zjhuntin — APPROVED** [review]

**Comment by Odilhao** [comment]
```
koji add-pkg --owner kojiadm  pulpcore-3.16-el7 tfm-pulpcore-python-pulp_manifest
Adding 1 packages to tag pulpcore-3.16-el7
koji add-pkg --owner kojiadm  pulpcore-3.16-el8 python-pulp_manifest
Adding 1 packages to tag pulpcore-3.16-el8

```

**Comment by ekohl** [comment]
@Odilhao this package is not present in `rpm/3.18`. Is that intentional?

**Comment by Odilhao** [comment]
> @Odilhao this package is not present in `rpm/3.18`. Is that intentional?

It's not, I'll branch for both 3.18 and 3.21, it was not branched when it was 1st added into 3.14

**Comment by maximiliankolb** [comment]
Thank you @Odilhao

**Pull request merged**
