### PR TITLE
mark Django 2.2.21+ not supported for pulp-container

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
this is due to the fact that epel8 now has a newer django, and our pipeline fail with that. I am not even sure this will help, but let's at least document it properly in the package :D

**Review by ekohl — APPROVED** [review]
Is it possible to specify a narrower range using rich dependencies?

**Comment by evgeni** [comment]
> Is it possible to specify a narrower range using rich dependencies?

Maybe… I didn't try so far.

**Comment by evgeni** [comment]
> I am not even sure this will help, but let's at least document it properly in the package :D

it did help, our pipelines are passing again, yay

**Pull request merged**
